### ISSUE TITLE
Generación de Codigo de Defecto 

### ISSUE THREAD

**Issue by giraffeman123** [giraffeman123/ReportSystemServer#30]
**Describe el error**
Tras eliminar un código de defecto de una familia especifica resulta problemas tras dar de alta un nuevo registro de esa familia al generar un nuevo codigo, provocando que se puedan repetir codigos. 

**Para Reproducirse**
Pasos para reproducir el comportamiento del error(ejemplo):
1. Ir al servidor usando Netbeans
2. Ejecutar la capa servicio
3. Eliminar un registro con un area y maquina especifico
4. Registrar un nuevo código con la misma area y maquina del registro eliminado
5. Observar el error de duplicidad de codigo

**Comportamiento esperado**
Ejemplo: existen 2 registro[FLM-1,FLM-2], eliminó FLM-1, a la hora de generar un nuevo código el sistema contara el unico registro existente en la bd[FLM-2] y le sumara al contador más uno, lo que provocaria que se repita el mismo registro[FLM-2]. 

**Screenshots**
Si es posible, añadir screenshots para explicar tu problema.

**Desktop (favor de llenar la siguiente información):**
 - TomCat Apache Version: [e.g. 8.0]
 - Netbeans o IDE utilizado[NetBeans]
 - Browser [chrome]
 - Version [1.0]

**Contexto Addicional**
Añadir de ser necesario mas cosas sobre el problema aqui.

**Comment by giraffeman123** [comment]
@Garfel agregó la siguiente validación en el metodo ObtenerCodigoDefecto
![image](https://user-images.githubusercontent.com/36062624/58767621-01bd5880-8543-11e9-8b42-9622a1da6ab4.png)

**Comment by Garfel** [comment]
Gracias por documentar el error compañero!
